### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RohanKarimi** [Reventaine/OpenAI-Telegram-Bot#2]
Hi
I hope you are doing well
I have an issue with the first running the code
I faced this error

`2023-04-09 03:24:01,482 - openai - INFO - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False`

What is the reason for it?
Because I have a Free trial usage on Open ai

![image](https://user-images.githubusercontent.com/53421893/230749670-249f092b-28f5-47b8-8e41-1c07ef2e6811.png)

**Comment by Reventaine** [comment]
Hello! The error clearly states that you have used up your free tokens. GPT-3.5 Turbo costs $0.002 per 1K tokens, OpenAI has given you $5 and 3 months as a free trial, after which you need to attach a credit card to your OpenAI account.
More information on this can be found on the official OpenAI website:
https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial
https://openai.com/pricing
